version: '3'

services:
  front-end:
    image: softy-pinko-front-end:task4
    build:
      context: ./front-end
    ports:
      - "9000:9000"

  back-end:
    image: softy-pinko-back-end:task4
    build:
      context: ./back-end
    ports:
      - "5252:5252"  # expose port 5252 de l'API Flask