# chercher dernière version ubuntu
FROM ubuntu:latest

# maj des paquets
RUN apt-get update

# Mise à niveau des paquets
RUN apt-get upgrade -y

# Afficher Hello, World ! 
CMD ["echo", "Hello, World!"]
